### ISSUE TITLE
[Learn][Campaigns] Add data about # of deployed  characters in specific battle (requested by ForgottenSaber)

### ISSUE THREAD

**Issue by svehera** [svehera/tacticusplanner#130]
ForgottenSaber — 31/12/2023 17:50
For the campaign learn pages, especially the elite campaigns, a column indicating the allowed number of deployed characters would be nice. I found out I didn’t need to upgrade Godswyll and Thoread at all for Oct ME because there aren’t any 3-man only levels. Knowing if/how far along 3-man levels exist in the elite campaigns will help determine how much you need to gear up the core three units for the campaign

**Comment by ErnstHB** [comment]
This would be part of the required data for https://github.com/svehera/tacticusplanner/issues/139
So I can take care of this one, and later add it onto that other request.
