### ISSUE TITLE
missing item in inventory

### ISSUE THREAD

**Issue by runiArnsbjornson** [svehera/tacticusplanner#156]
Some item are not in the actual inventory (exemple : transdimensional sanctum) i haven't checked all items, but if this one is missing some other might also be missing

**Comment by svehera** [comment]
@runiArnsbjornson transdimensional sanctum is a craftable item you need to toggle "Show craftable items" to show all crafted item too
https://tacticus.fandom.com/wiki/Transdimensional_Sanctum
![image](https://github.com/svehera/tacticusplanner/assets/33064347/804251d7-14db-4a41-b171-0152bba0b131)
