### ISSUE TITLE
incoherence in character input

### ISSUE THREAD

**Issue by runiArnsbjornson** [svehera/tacticusplanner#157]
While it's impossible to enter an imcompatible number of stars if a character is at a low rarity level, it is still possible to enter impossible star amount for legendary rarity. It's not a bug per se but it's not very consistent. Also the fact that when you unlock a character the level is set as 1 (because lvl 0 is impossible), but the capacity are set at 0 is the same. It seems the app automatically adjust to the closest possible but even so.
Also i know you are supposed to do this one big time and then update after, but still i think it could be cool to make it awesome, because it is atm the best tool to manage roasters

**Comment by NickReinlein** [comment]
This should be fixed with the merge of #184 
Now the number of stars available to select from the drop-down menu is limited to what is possible with that rarity
