### ISSUE TITLE
Double Tap Icon to Increase Inventory

### ISSUE THREAD

**Issue by MHURF** [svehera/tacticusplanner#159]
![image](https://github.com/svehera/tacticusplanner/assets/70976768/2f81c8f0-8484-470e-9a95-cf4be9d4716e)

Overview:
Add a double-click feature to Desktop and Mobile versions to increase inventory counts by one. Avoiding the need to manually type inventory adjustments.

Feature Details:
Users should be able to double-click/double tap on inventory icons to increase inventory count by 1. 

Optional Feature:
Add a Settings area to toggle this feature on/off if desired

Benefits:

Efficiency: Saves time and reduces errors by reducing manual input and typing required. Especially when farming items, receiving singular items from crates or purchasing items from the shop

**Comment by svehera** [comment]
Added + - buttons
